### ISSUE TITLE
Issues with plot rendering

### ISSUE THREAD

**Issue by fzabaleta** [timofeymukha/turbulucid#10]
When I plot the results from a simulation, I get a grainy plot using turblucid (see attached image). 
![Grainy image](https://user-images.githubusercontent.com/37196128/174690388-7d66e665-e9b1-4a0e-b441-fd81d09a6d13.png)
When I zoom in, the graininess of the image disappears :
![Zoomed image](https://user-images.githubusercontent.com/37196128/174690398-9d5401b9-7941-4490-a791-a3a54c7d924a.png)

This behavior may be related to the fact that the simulation was performed with an unstructured mesh so matplotlib has problems rendering it. 

Sorry I cannot be more specific, but I do not know how to describe this problem with more detail.

**Comment by timofeymukha** [comment]
Hi! Unstructured meshes shouldn't be an issue, this is kind of the whole point of turbulucid. The zoomed-up version looks ok to me, or? In the top plot the length of the axes is very different in x and y, I think that might be the cause of the patterns one sees. That won't be possible to fix I'm afraid because it's simply some matplotlib artistry, which we have no control over.

**Comment by fzabaleta** [comment]
Yes I suspected it was a matplotlib issue, but I was not able to find any solution online. Thanks for your help anyway and for such a great contribution
