### ISSUE TITLE
store data in .vtm format from OpenFoam simulation

### ISSUE THREAD

**Issue by surajp92** [timofeymukha/turbulucid#3]
I have some results in the VTK format form my OpenFoam simulation (generated with foamToVTK). Can I use this vtk file for plotting? When I try to use this VTK file, I got an indexing error "IndexError: tuple index out of range". If I save my data in the .vtm format form paraview and try to load the .vtm file, I am still getting an error "'VTKNoneArray' object has no attribute 'GetNumberOfValues'". How are you storing your data into .ntm format from OpenFoam simulation?

**Comment by timofeymukha** [comment]
Hi!

foamToVtk will produce 3d data if you have a 3d case, so that is not suitable for input. If you have a 2d case, then things should maybe work, but I have admittedly not tried. The best idea is to extract a slice from Paraview. You will typically get a .vtm file, but you don't need that one, instead use the .vtp that is also generated by Paraview and put in a folder with the same name. I show the process in this  [video](https://youtu.be/mTt_zNeR6A8).

Generating a .vtm for turbulucid is not easy. I use it with a very specialized tool that is not suitable for a general flow. But the only advantage of this .vtm over a standard .vtp extracted from paraview is only the decomposition of the boundary data into named portions. It's handy, but not really necessary.

**Comment by surajp92** [comment]
Thank you very much. I am able to work with .vtp files now. I didn't know about your video tutorials. Thank you for your help.
